services:
  webserver:
    build:
      dockerfile: DockerfileNginx
      context: .
    volumes:
      - sock:/var/run/php/
      - docroot:/var/www/html/

    ports:
      - "80:80"
  phpfpm:
    build:
      dockerfile: DockerfileFPM
      context: .
    volumes:
      - sock:/var/run/php/
      - docroot:/var/www/html/:ro
  
volumes:
  sock:
  docroot: